server:
    port:8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/delivery_tracking
        username: postgres
        password: 123123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true
    jackson:
        serialization:
            fail-on-empty-beans: false
docusign:
    integration-key: "cb18bc38-1aab-42e7-8240-3a2ec642db0d"
    user-id: "1ba00d72-307f-4489-bf00-0f8a1442d19e"
    account-id: "026b36e4-fbe5-4f4b-bedb-c761f84161ec"
    private-key-path: "private.key"
    auth-server: "account-d.docusign.com"